Modify CMakeLists to fix build errors.
This change bumps our C++ version to 17 and disables specific warnings
that cause build errors.

I was hitting three build errors, possibly due to the newer compiler:
- lang/c++/impl/Compiler.cc:304:18: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
- /usr/include/boost/math/tools/config.hpp:23:6: error: #warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)" [-Werror=cpp]
- avro/lang/c++/include/avro/Reader.hh:89:17: error: ‘v.avro::ReaderImpl<avro::NullValidator>::readValue(double&)::<unnamed union>::d’ may be used uninitialized [-Werror=maybe-uninitialized]

The last one only occurred during `./build.sh install`, not during `./build.sh test`

(cherry picked from commit d0967f565b521f0301b6bf792f74446d429c439e)