Inherit from public std::enable_shared_from_this
Modify the `Node` class to inherit from `std::enable_shared_from_this`
with `public` instead of `protected`. This to make clang-12 happy with
regards to:

```
[53/60] Performing build step for 'avro'
FAILED: avro-prefix/src/avro-stamp/avro-build
cd /ws/redpanda/build/deps_build/avro-prefix/src/avro-build && ninja avrocpp avrocpp_s avrogencpp && /usr/bin/cmake -E touch /ws/redpanda/build/deps_build/avro-prefix/src/avro-stamp/avro-build
[1/39] Building CXX object CMakeFiles/avrocpp_s.dir/impl/GenericDatum.cc.o
FAILED: CMakeFiles/avrocpp_s.dir/impl/GenericDatum.cc.o
/usr/bin/clang++-12 -DAVRO_SOURCE -DSNAPPY_CODEC_AVAILABLE -I/ws/redpanda/build/deps_build/avro-prefix/src/avro/lang/c++/api -I. -I/ws/redpanda/build/deps_install/include -fPIC -fcolor-diagnostics -std=c++20 -O3 -DNDEBUG -fPIC   -std=c++11 -fPIC -std=c++20 -MD -MT CMakeFiles/avrocpp_s.dir/impl/GenericDatum.cc.o -MF CMakeFiles/avrocpp_s.dir/impl/GenericDatum.cc.o.d -o CMakeFiles/avrocpp_s.dir/impl/GenericDatum.cc.o -c /ws/redpanda/build/deps_build/avro-prefix/src/avro/lang/c++/impl/GenericDatum.cc
In file included from /ws/redpanda/build/deps_build/avro-prefix/src/avro/lang/c++/impl/GenericDatum.cc:19:
In file included from /ws/redpanda/build/deps_build/avro-prefix/src/avro/lang/c++/api/GenericDatum.hh:34:
In file included from /ws/redpanda/build/deps_build/avro-prefix/src/avro/lang/c++/api/Node.hh:25:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/memory:77:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr.h:53:
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:1380:66: error: cannot cast 'avro::NodePrimitive' to its protected base class 'const std::enable_shared_from_this<avro::Node>'
          if (auto __base = __enable_shared_from_this_base(_M_refcount, __p))
                                                                        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:1343:4: note: in instantiation of function template specialization 'std::__shared_ptr<avro::NodePrimitive, __gnu_cxx::_S_atomic>::_M_enable_shared_from_this_with<avro::NodePrimitive, avro::NodePrimitive>' requested here
        { _M_enable_shared_from_this_with(_M_ptr); }
          ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr.h:409:4: note: in instantiation of function template specialization 'std::__shared_ptr<avro::NodePrimitive, __gnu_cxx::_S_atomic>::__shared_ptr<std::allocator<avro::NodePrimitive>, avro::Type>' requested here
        : __shared_ptr<_Tp>(__tag, std::forward<_Args>(__args)...)
          ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr.h:862:14: note: in instantiation of function template specialization 'std::shared_ptr<avro::NodePrimitive>::shared_ptr<std::allocator<avro::NodePrimitive>, avro::Type>' requested here
      return shared_ptr<_Tp>(_Sp_alloc_shared_tag<_Alloc>{__a},
             ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr.h:878:19: note: in instantiation of function template specialization 'std::allocate_shared<avro::NodePrimitive, std::allocator<avro::NodePrimitive>, avro::Type>' requested here
      return std::allocate_shared<_Tp>(std::allocator<_Tp_nc>(),
                  ^
/ws/redpanda/build/deps_build/avro-prefix/src/avro/lang/c++/api/NodeImpl.hh:436:27: note: in instantiation of function template specialization 'std::make_shared<avro::NodePrimitive, avro::Type>' requested here
         NodePtr key(std::make_shared<NodePrimitive>(AVRO_STRING));
                          ^
/ws/redpanda/build/deps_build/avro-prefix/src/avro/lang/c++/api/Node.hh:89:24: note: declared protected here
class AVRO_DECL Node : protected std::enable_shared_from_this<Node>,
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```